version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  directory: "."
  default_assignees:
    # update to your username :party:
    - "HugoDF"
  automerged_updates:
    - match:
      dependency_type: "all"
      update_type: "all"
